language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl
    - LISP=ccl

install:
  # Install cl-travis
  - curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | sh
  # Always use the latest Serapeum.
  - git clone --depth=1 https://github.com/ruricolist/serapeum.git ~/lisp/serapeum

script:
  - cl -l fiveam -l FXML -l FXML/test
       -e '(setf fiveam:*on-error* :debug
                 fiveam:*on-failure* :debug)'
       -e '(setf *debugger-hook*
                 (lambda (c h)
                   (declare (ignore c h))
                   (uiop:quit -1)))'
       -e '(or (fxml.test:run-tests) (uiop:quit 1))'
